### PR TITLE
Make into package

### LINKED ISSUE #5: Make package installable
WIP on the [fix/install](https://github.com/alan-turing-institute/repro-catalogue/tree/fix/install) branch.

### LINKED ISSUE #7: Create `construct_dict` function
Subtask of #6 

This function is called in [engage.py](https://github.com/alan-turing-institute/repro-catalogue/blob/2745de147f5cb0ba5c8e045e03c868dcbe3d1682/catalogue/engage.py#L24)

### LINKED ISSUE #8: Implement timestamps
Subtask of #6

In [engage.py](https://github.com/alan-turing-institute/repro-catalogue/blob/2745de147f5cb0ba5c8e045e03c868dcbe3d1682/catalogue/engage.py) a timestamp variable is meant to be set in each function.

### PR DESCRIPTION
**Pull request by radka-j**
Closes #5
Closes #7 
Closes #8 

- adds setup.py and init files
- fixes syntax errors
- adds placeholders for functions to be implemented
- adds `construct_dict` function
- adds `create_timestamp` function

It should be possible to install the package and run `engage` and `disengage`. This doesn't do anything at the moment.

### CODE REVIEW

**Review by edaub — APPROVED** [review]
Looks fine to me for the most part. I assume we will want to rework things so that `main` is accessible from a command line invocation of `catalogue <options>` rather than `python parser.py <options>`, but will file that as a separate issue.

**Comment by radka-j** [comment]
In the current implementation if you install the package you can run `catalogue engage <args>` and `catalogue disengage <args>` from the command line. Is that what you mean or do you have something else in mind?

**Comment by radka-j** [comment]
Closes #18 

The `main` function in `parser.py` is a command line entry point in `setup.py`.

**Comment by edaub** [comment]
Yes, I didn't realize that! You learn something new every day...

**Pull request merged**
