### PR TITLE
Feature/csv

### PR DESCRIPTION
**Pull request by edaub**
Adds support for a CSV backend. When calling `disengage`, setting the `--csv` flag will save the hash records to a CSV file in the `catalogue_results` directory rather than a json dump. If an existing file is given, it appends, otherwise it creates a new file.

`compare` mode can similarly use the `--csv` option to compare hashes based on the timestamp.

* Implements `load_csv` and `save_csv` functions
* Modifications to `disengage` and `compare`
* Added `--csv` flag to the parser and modified the `check_paths_exists` function to set the csv path

### CODE REVIEW

**Review by radka-j — APPROVED** [review]
Looks good!

Minor comment, I get an error if I just use `--csv` and I have to call `--csv csv` instead. Changing the parser to something like below should fix this: 
```
(output_parser.add_argument( "--csv",  action='store_true')
```

I am a bit unsure what the output of `compare` is if the csv has more than 2 lines and I only provide one timestamp for comparison. It might be nice to print out which timestamps are being compared. Maybe we should also print what json files are being compared for consistency although it's less necessary there. But we can open this up as an issue to tackle later.

We should also add the csv functionality to the README and add tests. But again, lets open up an issue for these.

**Comment by edaub** [comment]
`--csv` requires an argument to follow as it needs a filename the way I have written the function. We can alternatively set a standard value for the CSV file and then just use `--csv` as you suggest, which I think would be a perfectly fine way to do things as well (and we could also add a `--json` option if they wanted multiple output formats from the same run). I would welcome input from anyone on this, happy to tweak this based on how we think people would want to use it.

**Comment by radka-j** [comment]
I wasn't paying enough attention, sorry!

I think leaving the `--csv` flag as is makes sense.

I also just realised my second comment is unnecessary. If you provide one timestamp, then that is compared with the current state of the CWD correct? That seems pretty clear.

**Comment by edaub** [comment]
Yes, that is how the current behavior is configured if only one timestamp is given. I have run it through some informal tests, and now that you have some tests written I will try to incorporate them in as well.

**Pull request merged**
